name: CMake Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Paths
      run: |
        echo "Current directory: $(pwd)"
        ls -la
        echo "Contents of workspace:"
        ls -la ${{ github.workspace }}

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake ${{ github.workspace }} -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release || { echo "CMake configuration failed"; exit 1; }
        ls -la

    - name: Build Project
      run: |
        cd build
        cmake --build . || { echo "Build failed"; exit 1; }

    - name: Run Tests
      run: |
        cd build
        ./SKT_Lab02 || { echo "Test run failed"; exit 1; }
