name: CMake Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Paths
      run: |
        echo "Current directory: $(pwd)"
        ls -la
        echo "Contents of skt_lab02:"
        ls -la skt_lab02

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake ../skt_lab02 -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release || { echo "CMake configuration failed"; exit 1; }

    - name: Build Project
      run: |
        cd build
        cmake --build . || { echo "Build failed"; exit 1; }
    - name: Make artifact
      uses: actions/upload-artifact@v3
      with:
        name: SKT_lab02
        path: dist/*
